export const GET_DETAIL_USER_PENDING = 'GET_DETAIL_USER_PENDING';
export const GET_DETAIL_USER_SUCCESS = 'GET_DETAIL_USER_SUCCESS';
export const GET_DETAIL_USER_FAILED = 'GET_DETAIL_USER_FAILED';

export const GET_LIST_USER_PENDING = 'GET_LIST_USER_PENDING';
export const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
export const GET_LIST_USER_FAILED = 'GET_LIST_USER_FAILED';

export const GET_LIST_STORE_PENDING = 'GET_LIST_STORE_PENDING';
export const GET_LIST_STORE_SUCCESS = 'GET_LIST_STORE_SUCCESS';
export const GET_LIST_STORE_FAILED = 'GET_LIST_STORE_FAILED';

export const GET_DETAIL_PRODUCT_PENDING = 'GET_DETAIL_PRODUCT_PENDING';
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';
export const GET_DETAIL_PRODUCT_FAILED = 'GET_DETAIL_PRODUCT_FAILED';

export const GET_LIST_PRODUCT_PENDING = 'GET_LIST_PRODUCT_PENDING';
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';
export const GET_LIST_PRODUCT_FAILED = 'GET_LIST_PRODUCT_FAILED';

export const GET_LIST_TRANSACTION_PENDING = 'GET_LIST_TRANSACTION_PENDING';
export const GET_LIST_TRANSACTION_SUCCESS = 'GET_LIST_TRANSACTION_SUCCESS';
export const GET_LIST_TRANSACTION_FAILED = 'GET_LIST_TRANSACTION_FAILED';

export const GET_DETAIL_TRANSACTION_PENDING = 'GET_DETAIL_TRANSACTION_PENDING';
export const GET_DETAIL_TRANSACTION_SUCCESS = 'GET_DETAIL_TRANSACTION_SUCCESS';
export const GET_DETAIL_TRANSACTION_FAILED = 'GET_DETAIL_TRANSACTION_FAILED';

export const GET_LIST_BRAND_PENDING = 'GET_LIST_BRAND_PENDING';
export const GET_LIST_BRAND_SUCCESS = 'GET_LIST_BRAND_SUCCESS';
export const GET_LIST_BRAND_FAILED = 'GET_LIST_BRAND_FAILED';

export const GET_DETAIL_BRAND_PENDING = 'GET_DETAIL_BRAND_PENDING';
export const GET_DETAIL_BRAND_SUCCESS = 'GET_DETAIL_BRAND_SUCCESS';
export const GET_DETAIL_BRAND_FAILED = 'GET_DETAIL_BRAND_FAILED';

export const GET_LIST_CATEGORY_PENDING = 'GET_LIST_CATEGORY_PENDING';
export const GET_LIST_CATEGORY_SUCESS = 'GET_LIST_CATEGORY_SUCESS';
export const GET_LIST_CATEGORY_FAILED = 'GET_LIST_CATEGORY_FAILED';

export const GET_DETAIL_CATEGORY_PENDING = 'GET_DETAIL_CATEGORY_PENDING';
export const GET_DETAIL_CATEGORY_SUCCESS = 'GET_DETAIL_CATEGORY_SUCCESS';
export const GET_DETAIL_CATEGORY_FAILED = 'GET_DETAIL_CATEGORY_FAILED';
